### PR TITLE
Added the death animations

### LINKED ISSUE #174: Enemy death animation
- There is a death animation that plays when an enemy dies
- Maybe the goblins and trolls on their side, faces covered in poo?

### PR DESCRIPTION
**Pull request by EthanHair**
Added the death animations for the troll and goblin

closes #174

### CODE REVIEW

**Comment by Psypher9** [comment]
I'm seeing that we might benefit from having an `Enemy` node to contain some of the duplicate code. It looks like The `Goblin` and `Troll` nodes would inherit from that type and have their stats and sprites tweaked a bit. What do you think?

**Comment by EthanHair** [comment]
Can we do class inheritance like that in gdscript?

**Comment by Psypher9** [comment]
Yeah we can, any time we add a script to a Node, it's actually extending the type of that Node. That's why when we add a Script to a Node for an Area or a Kinematic body, we can use those signals.

**Comment by EthanHair** [comment]
Lol yeah I just realized that's how all the nodes work. Yeah I can work on making that change

**Review by caldane — APPROVED** [review]

**Pull request merged**
